"""add lifetime analysis quota

Revision ID: 19281db0acc4
Revises: 0439523a12ec
Create Date: 2026-08-04 23:20:29.103486

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '19281db0acc4'
down_revision = '0439523a12ec'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('messages', schema=None) as batch_op:
        batch_op.add_column(sa.Column('quota_refunded', sa.Boolean(), server_default=sa.false(), nullable=False))

    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.add_column(sa.Column('analyses_used', sa.Integer(), server_default='0', nullable=False))
        batch_op.add_column(sa.Column('nothing_to_show_refunds_used', sa.Integer(), server_default='0', nullable=False))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.drop_column('nothing_to_show_refunds_used')
        batch_op.drop_column('analyses_used')

    with op.batch_alter_table('messages', schema=None) as batch_op:
        batch_op.drop_column('quota_refunded')

    # ### end Alembic commands ###
