"""remove index=True from user_id column

Revision ID: 307843e56a0a
Revises: f64941688456
Create Date: 2026-05-16 23:08:04.162579

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '307843e56a0a'
down_revision = 'f64941688456'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('notifications', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_notifications_user_id'))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('notifications', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_notifications_user_id'), ['user_id'], unique=False)

    # ### end Alembic commands ###
