"""add message_id to notifications

Revision ID: 3a969820e549
Revises: 19281db0acc4
Create Date: 2026-08-11 00:12:04.131165

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '3a969820e549'
down_revision = '19281db0acc4'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('notifications', schema=None) as batch_op:
        batch_op.add_column(sa.Column('message_id', sa.Integer(), nullable=True))
        batch_op.create_index(batch_op.f('ix_notifications_message_id'), ['message_id'], unique=False)
        batch_op.create_foreign_key('fk_notifications_message_id_messages', 'messages', ['message_id'], ['id'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('notifications', schema=None) as batch_op:
        batch_op.drop_constraint('fk_notifications_message_id_messages', type_='foreignkey')
        batch_op.drop_index(batch_op.f('ix_notifications_message_id'))
        batch_op.drop_column('message_id')

    # ### end Alembic commands ###
