"""add index and unique to user field

Revision ID: 3f018d6271e3
Revises: 521a1f1ab3e9
Create Date: 2026-04-17 14:38:24.269772

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '3f018d6271e3'
down_revision = '521a1f1ab3e9'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_users_verification_token'), ['verification_token'], unique=True)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_users_verification_token'))

    # ### end Alembic commands ###
