"""add pasword reset token fields to user

Revision ID: 809e73481aec
Revises: 3f018d6271e3
Create Date: 2026-04-19 20:51:13.442871

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '809e73481aec'
down_revision = '3f018d6271e3'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.add_column(sa.Column('password_reset_token', sa.String(length=100), nullable=True))
        batch_op.add_column(sa.Column('password_reset_expires_at', sa.DateTime(timezone=True), nullable=True))
        batch_op.create_index(batch_op.f('ix_users_password_reset_token'), ['password_reset_token'], unique=True)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_users_password_reset_token'))
        batch_op.drop_column('password_reset_expires_at')
        batch_op.drop_column('password_reset_token')

    # ### end Alembic commands ###
