"""rename the password to password_hash in user

Revision ID: 840dca948f3c
Revises: 2ccbfea9c30e
Create Date: 2026-03-16 22:56:23.192963

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '840dca948f3c'
down_revision = '2ccbfea9c30e'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.add_column(sa.Column('password_hash', sa.String(length=255), nullable=False))
        batch_op.drop_column('password')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.add_column(sa.Column('password', sa.VARCHAR(length=255), nullable=False))
        batch_op.drop_column('password_hash')

    # ### end Alembic commands ###
