"""add due_text to tasks

Revision ID: 84534747c090
Revises: dc10b8d5784c
Create Date: 2026-08-16 11:52:57.268022

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '84534747c090'
down_revision = 'dc10b8d5784c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('tasks', schema=None) as batch_op:
        batch_op.add_column(sa.Column('due_text', sa.String(length=120), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('tasks', schema=None) as batch_op:
        batch_op.drop_column('due_text')

    # ### end Alembic commands ###
