"""Add detected_language to AnalysisResult

Revision ID: 9e6f84eddda7
Revises: d8e9ad670217
Create Date: 2026-04-11 00:29:19.633194

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '9e6f84eddda7'
down_revision = 'd8e9ad670217'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('analysis_results', schema=None) as batch_op:
        batch_op.add_column(sa.Column('detected_language', sa.String(length=15), nullable=True))
        batch_op.create_index(batch_op.f('ix_analysis_results_detected_language'), ['detected_language'], unique=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('analysis_results', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_analysis_results_detected_language'))
        batch_op.drop_column('detected_language')

    # ### end Alembic commands ###
