"""Initial database schema

Revision ID: b7c4fb97cf9b
Revises: 
Create Date: 2026-03-10 11:02:38.422579

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'b7c4fb97cf9b'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('messages',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('subject', sa.String(length=255), nullable=True),
    sa.Column('sender_email', sa.String(length=255), nullable=True),
    sa.Column('raw_text', sa.Text(), nullable=False),
    sa.Column('status', sa.String(length=30), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('messages', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_messages_sender_email'), ['sender_email'], unique=False)
        batch_op.create_index(batch_op.f('ix_messages_status'), ['status'], unique=False)

    op.create_table('agent_runs',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('message_id', sa.Integer(), nullable=False),
    sa.Column('agent_name', sa.String(length=50), nullable=False),
    sa.Column('selected_tools', sa.JSON(), nullable=True),
    sa.Column('decision_reason', sa.Text(), nullable=True),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['message_id'], ['messages.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('agent_runs', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_agent_runs_status'), ['status'], unique=False)

    op.create_table('analysis_results',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('message_id', sa.Integer(), nullable=False),
    sa.Column('message_category', sa.String(length=100), nullable=True),
    sa.Column('category_confidence', sa.Float(), nullable=True),
    sa.Column('urgency_level', sa.String(length=50), nullable=True),
    sa.Column('urgency_confidence', sa.Float(), nullable=True),
    sa.Column('job_field', sa.String(length=100), nullable=True),
    sa.Column('job_field_confidence', sa.Float(), nullable=True),
    sa.Column('company_name', sa.String(length=255), nullable=True),
    sa.Column('role_title', sa.String(length=255), nullable=True),
    sa.Column('interview_stage', sa.String(length=100), nullable=True),
    sa.Column('interview_format', sa.String(length=100), nullable=True),
    sa.Column('date_text', sa.String(length=100), nullable=True),
    sa.Column('time_text', sa.String(length=100), nullable=True),
    sa.Column('location_text', sa.String(length=255), nullable=True),
    sa.Column('scheduled_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('processed_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('preparation_guidance', sa.Text(), nullable=True),
    sa.Column('suggested_questions', sa.Text(), nullable=True),
    sa.Column('reply_suggestions', sa.Text(), nullable=True),
    sa.Column('archive_summary', sa.Text(), nullable=True),
    sa.Column('role_summary', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['message_id'], ['messages.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('message_id')
    )
    op.create_table('tasks',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('message_id', sa.Integer(), nullable=False),
    sa.Column('task_name', sa.String(length=255), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('due_date', sa.DateTime(timezone=True), nullable=True),
    sa.Column('priority', sa.String(length=20), nullable=False),
    sa.Column('is_completed', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['message_id'], ['messages.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('tasks', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_tasks_is_completed'), ['is_completed'], unique=False)
        batch_op.create_index(batch_op.f('ix_tasks_priority'), ['priority'], unique=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('tasks', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_tasks_priority'))
        batch_op.drop_index(batch_op.f('ix_tasks_is_completed'))

    op.drop_table('tasks')
    op.drop_table('analysis_results')
    with op.batch_alter_table('agent_runs', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_agent_runs_status'))

    op.drop_table('agent_runs')
    with op.batch_alter_table('messages', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_messages_status'))
        batch_op.drop_index(batch_op.f('ix_messages_sender_email'))

    op.drop_table('messages')
    # ### end Alembic commands ###
