"""add job_application FK and relationship to message

Revision ID: e9112939193e
Revises: 8fcc55fd0dc6
Create Date: 2026-04-15 01:00:06.968701

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'e9112939193e'
down_revision = '8fcc55fd0dc6'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('messages', schema=None) as batch_op:
        batch_op.add_column(sa.Column('job_application_id', sa.Integer(), nullable=True))
        batch_op.create_index(batch_op.f('ix_messages_job_application_id'), ['job_application_id'], unique=False)
        batch_op.create_foreign_key('fk_messages_job_application_id', 'job_applications', ['job_application_id'], ['id'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('messages', schema=None) as batch_op:
        batch_op.drop_constraint('fk_messages_job_application_id', type_='foreignkey')
        batch_op.drop_index(batch_op.f('ix_messages_job_application_id'))
        batch_op.drop_column('job_application_id')

    # ### end Alembic commands ###
